# Generated by Django 4.2.11 on 2024-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
