# Generated by Django 4.2.11 on 2024-03-09 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_review_rename_phone_reservation_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[(datetime.time(17, 0), '17:00 PM'), (datetime.time(18, 0), '18:00 PM'), (datetime.time(19, 0), '19:00 PM'), (datetime.time(20, 0), '20:00 PM'), (datetime.time(21, 0), '21:00 PM'), (datetime.time(22, 0), '22:00 PM'), (datetime.time(23, 0), '23:00 PM')]),
        ),
    ]
