# Generated by Django 4.2.11 on 2024-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_reservation_number_of_people_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1),
        ),
    ]
