# Generated by Django 4.2.11 on 2024-03-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
