# Generated by Django 4.2.11 on 2024-03-14 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_reservation_approved_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[('17:00', '17:00 PM'), ('18:00', '18:00 PM'), ('19:00', '19:00 PM'), ('20:00', '20:00 PM'), ('21:00', '21:00 PM'), ('22:00', '22:00 PM'), ('23:00', '23:00 PM')], validators=[django.core.validators.RegexValidator(message='Time must be between 5:00 PM and 11:00 PM', regex='^([1][7-9]|20|21|22|23):00$')]),
        ),
    ]
